global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "grafana"
    scrape_interval: 2m
    static_configs:
    - targets: ["grafana:3000"]

  - job_name: "node"
    scrape_interval: 10s
    static_configs:
    - targets: ["node-exporter:9100"]


  - job_name: "dcgm"
    scrape_interval: 20s
    static_configs:
    - targets: ["dcgm-exporter:9400"]

